image: circleci/node:10.15.3-browsers

cache:
  paths:
    - node_modules/

run_test:
  stage: test
  services:
  - mongo
  - name: selenium/standalone-chrome
    alias: selenium
  script:
  - npm install
  - npm run lint
  - npm run test:unit

  # This CI already includes MongoDB & Selenium services so
  # there's no need to self-start in-memory MongoDB and Selenium
  #- DISABLE_IN_MEMORY_MONGODB=true DISABLE_IN_MEMORY_SELENIUM=true DB_PORT=27017 DB_HOST=mongo SELENIUM_HOST=selenium npm run test:e2e
